### PR TITLE
Osx missing objcopy

### PR DESCRIPTION
**Pull request by TheWookie**
Long story short, osx needs objcopy to build even the examples at a basic level. This small change in the install_osx.sh file lets people know, up front, how to build the basic example projects.

### CODE REVIEW

**Comment by TheWookie** [comment]
Example output from `test.sh` without the export.

```
$ ./test.sh
~/git/IncludeOS/examples/demo_service ~/git/IncludeOS

>> Linking service with OS
/Users/paulbaker/IncludeOS_install/bin/ld -nostdlib -melf_i386 -N --eh-frame-hdr --script=/Users/paulbaker/IncludeOS_install/linker.ld --defsym _MAX_MEM_MIB_=128 --defsym=__stack_rand_ba=`date +%s` --strip-debug /Users/paulbaker/IncludeOS_install/crt/crtbegin.o /Users/paulbaker/IncludeOS_install/crt/crti.o /Users/paulbaker/IncludeOS_install/multiboot.o service.o .service_name.o /Users/paulbaker/IncludeOS_install/drivers/virtionet.o   /Users/paulbaker/IncludeOS_install/os.a /Users/paulbaker/IncludeOS_install/libcxx/libc++.a /Users/paulbaker/IncludeOS_install/libcxx/libc++abi.a /Users/paulbaker/IncludeOS_install/os.a /Users/paulbaker/IncludeOS_install/newlib/libc.a /Users/paulbaker/IncludeOS_install/newlib/libm.a /Users/paulbaker/IncludeOS_install/libgcc/libgcc.a /Users/paulbaker/IncludeOS_install/crt/crtend.o /Users/paulbaker/IncludeOS_install/crt/crtn.o  -o Demo_Service

>> Adding symbol section
/Users/paulbaker/IncludeOS_install/elf_syms Demo_Service
objcopy --update-section .elf_symbols=_elf_symbols.bin Demo_Service Demo_Service
make: objcopy: No such file or directory
make: *** [service] Error 1

INSTALL FAILED ON COMMAND: make
```

**Comment by AndreasAakesson** [comment]
Solves #884

**Comment by alfred-bratterud** [comment]
ok to test

**Comment by alfred-bratterud** [comment]
Thanks @TheWookie !

**Pull request merged**
