### PR TITLE
Use std::move

### PR DESCRIPTION
**Pull request by platayplataxplarti**

### CODE REVIEW

**Comment by ingve** [comment]
jenkins test please

**Comment by mnordsletten** [comment]
This failed due to an error in Openstack. Let me run the tests again, jenkins test please

**Comment by ingve** [comment]
Hi, thanks for your contribution! Unfortunately there is a merge conflict, could you update your PR by pulling the latest changes from the `dev` branch?

Also, if you could give us a little more information about *why* it is beneficial to use `std::move` in these cases? It would make it easier for those who will be reviewing your pull request.

**Comment by fwsGonzo** [comment]
If you still want to merge this, can you provide an explanation for why this is necessary?

**Pull request closed without merging**
