### PR TITLE
Fixed small errors in clean build

### PR DESCRIPTION
**Pull request by someonewithpc**

### CODE REVIEW

**Comment by ingve** [comment]
ok to test

**Comment by ingve** [comment]
Hi, and thanks for contributing! :+1:

Seems like there were some Jenkins test errors here. Our experts @mnordsletten and @staiyeba can hopefully figure out what's going on.

**Comment by mnordsletten** [comment]
Hi

Thanks for the PR.
This PR is made towards the `master` branch of IncludeOS. Please close and reopen towards the `dev` branch. A lot of improvements have been made to the dev branch tests.

**Comment by AndreasAakesson** [comment]
Please open a new PR to the dev branch. Closing this.

**Pull request closed without merging**
