### PR TITLE
IP4 addr operator overloading

### PR DESCRIPTION
**Pull request by AnnikaH**
- Bug fix operator >
- Added >= and <=

### CODE REVIEW

**Comment by fwsGonzo** [comment]
Can you clone dev from scratch and then create this change as a single commit?  It would reduce the number of commits greatly. 👍

**Comment by fwsGonzo** [comment]
Your commit named "IP4 addr operator overloading" has 14,000 changes now :P

**Comment by AnnikaH** [comment]
Hm yes, I used git reset --soft to remove all the Merge branch-commits, but then when committing, the earlier versions of the files where noted as changes to the branch, so I had to merge branch dev to get the latest. I can try to reset --soft again, but pull from dev before committing - hopfully that will work.

**Comment by AnnikaH** [comment]
Think that did the trick

**Pull request merged**
