### PR TITLE
Paging for amd64, coroutines/fibers, and more

### PR DESCRIPTION
**Pull request by fwsGonzo**

### CODE REVIEW

**Comment by fwsGonzo** [comment]
jenkins test please

**Comment by fwsGonzo** [comment]
jenkins test please

**Comment by mnordsletten** [comment]
Jenkins test please

**Comment by fwsGonzo** [comment]
jenkins test please

**Comment by fwsGonzo** [comment]
jenkins test please

**Comment by fwsGonzo** [comment]
jenkins test please

**Pull request merged**
