### PR TITLE
ethernet.hpp: Fix Ethernet MAC address string representation to print leading zeros 

### PR DESCRIPTION
**Pull request by RicoAntonioFelix**
# Change
* Fix Ethernet MAC address string representation to print leading zeros
* Added test folder for net::Ethernet module

### CODE REVIEW

**Comment by fwsGonzo** [comment]
ok to test

**Comment by fwsGonzo** [comment]
Looks like a minor change to add constructors to Ethernet addr is in order, to avoid double braces

**Comment by RicoAntonioFelix** [comment]
Should I also fix the IP4 errors from here as it runs with the test?

**Comment by fwsGonzo** [comment]
All tests have to pass

**Pull request merged**
