### PR TITLE
added check for lsb_release in install script

### PR DESCRIPTION
**Pull request by szborows**
I had no `lsb_release` installed on my system and `install.sh` complained the system was not supported at all.

### CODE REVIEW

**Comment by rianquinn** [comment]
@alfred-bratterud FYI... we had the same problem with lsb_release. We started using /etc/os-release instead which seems to be on most modern Linux distros.

**Comment by szborows** [comment]
retrieving this manually is a little bit trickier in `sh` than I initially though. apparently `sh` doesn't support arrays like `bash` does.
what do you think about following? can we assume we have `grep` and `cut` on the board?

```sh
grep "ID=" /etc/os-release | cut -c 4-
```

**Comment by alfred-bratterud** [comment]
Hi @szborows, thanks for contributing! Looks like both grep and cut are listed in [posix utilities](http://pubs.opengroup.org/onlinepubs/9699919799/idx/utilities.html), so those should be fine. I'll see if I can get the tests to pass. Jenkins test please.

**Comment by szborows** [comment]
actually there's a way to do this without cut:
```sh
LINE=`grep "ID=" /etc/os-release`
RELEASE=`echo "${XYZ##*=}"`
```

badum-tsss

**Comment by szborows** [comment]
are these tests inherently unstable?

**Comment by alfred-bratterud** [comment]
jenkins test please

**Pull request merged**
