### PR TITLE
net: Hotfix to ARP - sets eth header on packet chain (master)

### PR DESCRIPTION
**Pull request by AndreasAakesson**

### CODE REVIEW

**Comment by alfred-bratterud** [comment]
Thanks @AndreasAakesson. The tests fail due to posix tests not being present on master yet.

**Comment by AndreasAakesson** [comment]
I know the category has been added (twice) already on dev, but since its just one line I make a new commit. (and now it became two...)

**Comment by AndreasAakesson** [comment]
retest please

**Comment by mnordsletten** [comment]
Retest please

**Comment by mnordsletten** [comment]
Retest please

Now it should be fixed

**Pull request merged**
