### PR TITLE
fix panic on close or 2+ connections

### PR DESCRIPTION
**Pull request by SeanMooney**
- This change fixes the kernel panic when clients
  close the websocket.
- This change fixes the kernel panic when a second
  client connects to the websocket.

### CODE REVIEW

**Comment by SeanMooney** [comment]
the panic details can be found here
https://pastebin.com/Ymi4Yghr

**Comment by ingve** [comment]
jenkins test please

**Comment by ingve** [comment]
Nice catch, awesome bug report and fix! Thanks for contributing! 👍

**Comment by SeanMooney** [comment]
well i was watching the cppcon talk on includeos this weekend and decided to check it out.
i noticed you had just done a release and called out the websocket example so tried that out
after i got the basic demo running. 

i have to say includeos was remarkably easy to get started with compared to most cpp projects.
its a really cool project, looking forward to seeing how it progresses.

**Pull request merged**
