### PR TITLE
kernel: OS uptime is now using RTC + getter for CPU freq

### PR DESCRIPTION
**Pull request by AndreasAakesson**

### CODE REVIEW

**Comment by AndreasAakesson** [comment]
stl tests fails due to [exception test](https://github.com/hioa-cs/IncludeOS/blob/dev/test/stl/integration/exceptions/service.cpp#L38)

**Comment by alfred-bratterud** [comment]
test please

**Comment by alfred-bratterud** [comment]
test please

**Comment by fwsGonzo** [comment]
:+1:

**Pull request merged**
