### PR TITLE
Update api/common

### PR DESCRIPTION
**Pull request by RicoAntonioFelix**
## Changes
* Redefined termination policy for Expects and Ensures...

### CODE REVIEW

**Comment by fwsGonzo** [comment]
Cool :+1:

**Comment by alfred-bratterud** [comment]
Looks good @RicoAntonioFelix . Question: why the while-loops?

**Comment by fwsGonzo** [comment]
the while loops act as scope-creation helper, just like FreeBasics `scope` keyword:

http://www.freebasic.net/wiki/wikka.php?wakka=KeyPgScope

**Comment by alfred-bratterud** [comment]
And another thing: @RicoAntonioFelix - I was thinking we should probably use our own macro for enabling / disabling this mode, something like : `#ifdef ASSERT_ON_CONTRACT_VIOLATION`. This way we can keep the GSL versions completely unchanged. Thoughts?

**Comment by RicoAntonioFelix** [comment]
@alfred-bratterud Check out the updates from your suggestions...

**Pull request merged**
