### PR TITLE
Fix the breakage of booting solo5 using '--with-solo5' option

### PR DESCRIPTION
**Pull request by niks3089**
When I tried to run IncludeOS with solo5 with `boot --with-solo5 .`  I got the following error

```
Traceback (most recent call last):
  File "/home/osboxes/includeos//includeos/vmrunner/vmrunner.py", line 855, in boot
    self._hyper.boot(multiboot, debug, "booted with vmrunner", "udp_perf")
TypeError: boot() takes at most 4 arguments (5 given)
```

Looks like this because of a recent change (#1708) where the `debug` parameter was added to Qemu but not to ukvm.  I simply added the debug parameter and its a NO-OP for now

---
This change is [Reviewable](https://reviewable.io/reviews/hioa-cs/includeos/1726)

### CODE REVIEW

**Comment by ingve** [comment]
add to whitelist

**Comment by niks3089** [comment]
The unit test seems to be failing because of configuration issue and not my change? I see a similar log for a previous PR

**Comment by ingve** [comment]
jenkins test please

**Comment by AndreasAakesson** [comment]
I think you need to merge with latest dev due to build_examples timing out.

**Comment by niks3089** [comment]
Hey @AndreasAakesson , looks like merging also didn't help?

**Comment by AndreasAakesson** [comment]
It's due to this error here when building examples:
```
12:31:20 /home/ubuntu/workspace/workspace/pr_misc/IncludeOS_install/includeos/bin/elf_syms: Pruning ELF symbols 
12:31:20 ELF symbols: d644ea88  ELF strings: 9e59ec4a  ELF section: 4e0997e6
12:31:20 /usr/bin/objcopy: stsETCaO: section .bss lma 0x5c4000 adjusted to 0x673573
12:31:20 /usr/bin/strip: sttrpnEQ: section .bss lma 0x5c4000 adjusted to 0x673573
12:31:20 make[2]: *** [CMakeFiles/prepend_bootloader] Segmentation fault (core dumped)
12:31:20 make[1]: *** [CMakeFiles/prepend_bootloader.dir/all] Error 2
12:31:20 make: *** [all] Error 2
```
Haven't been able to reproduce it myself locally, we've only seen it on jenkins.

jenkins test please

**Comment by ingve** [comment]
Jenkins test please

**Pull request merged**
