### PR TITLE
demo_example rework

### PR DESCRIPTION
**Pull request by Voultapher**
My goals:
Show that it is more than a static website
Show it can have state across multiple sessions
Make it fun
Make it pretty

### CODE REVIEW

**Comment by Voultapher** [comment]
Forgot README, give me a second

**Comment by AndreasAakesson** [comment]
jenkins test please

**Comment by Voultapher** [comment]
I'm on it :+1:

**Comment by krzysztofwos** [comment]
Just being pedantic... rest of the code base uses rather consistently two spaces for indentation but this PR replaces that with tabs.

**Comment by alfred-bratterud** [comment]
Looks like there's not much activity on this. I wouldn't mind seeing something like this as a separate example under examples :-)

**Pull request closed without merging**
