### PR TITLE
diskimagebuild/writer.cpp: Refactor code to silence compiler warnings

### PR DESCRIPTION
**Pull request by RicoAntonioFelix**

### CODE REVIEW

**Comment by fwsGonzo** [comment]
jenkins test please

**Comment by AndreasAakesson** [comment]
@RicoAntonioFelix pull latest dev and try again :) the test should pass now.

**Comment by fwsGonzo** [comment]
jenkins test please

**Comment by RicoAntonioFelix** [comment]
@AndreasAakesson Saw this late...Guess it was good to go... :smile:

**Pull request merged**
