### PR TITLE
format: FileSystem changed to File_system (WIP - keep open)

### PR DESCRIPTION
**Pull request by alfred-bratterud**

### CODE REVIEW

**Comment by AndreasAakesson** [comment]
retest please

**Comment by alfred-bratterud** [comment]
test please

**Comment by alfred-bratterud** [comment]
retest please

**Comment by alfred-bratterud** [comment]
Previous test was aborted due to signal to clang for some reason.

**Comment by alfred-bratterud** [comment]
Test timed out. retest please.

**Comment by mnordsletten** [comment]
retest please
Added g++-multilib to all the pull request machines.

**Pull request merged**
