### PR TITLE
Fixed the test.py script that runs all the tests

### PR DESCRIPTION
**Pull request by mnordsletten**
There still seems to be some issue with vmrunner.py where it doesn't abort the test if the timeout is exceeded.

### CODE REVIEW

**Comment by mnordsletten** [comment]
Retest this please

Now updated jenkins to reflect the moved bufstore test.

**Comment by mnordsletten** [comment]
test this please

Now updated jenkins to reflect the moved bufstore test.

**Comment by mnordsletten** [comment]
Test please

Now updated jenkins to reflect the moved bufstore test.

**Comment by alfred-bratterud** [comment]
Nice!

**Pull request merged**
