### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by geisler**
These fixes were necessary to be able to run the install script on my machine.  They are simple and described in each commit message.

### CODE REVIEW

**Comment by ingve** [comment]
jenkins test please

**Comment by mnordsletten** [comment]
I also have a fix for the `install_from_bundle.sh` compiler check not working in my pr. This can still be merged and I can modify my pr to reflect this. 
What system are you using?

**Comment by geisler** [comment]
On Thu, Feb 23, 2017 at 12:03:01AM -0800, Martin Nordsletten wrote:
> I also have a fix for the `install_from_bundle.sh` compiler check not working in my pr. This can still be merged and I can modify my pr to reflect this. 
> What system are you using?

Debian stretch

						-- Jonathan Geisler --

**Comment by geisler** [comment]
Fixed conflicts from compiler check by just using the updated code in dev.
Also updated install.sh to export variables so it would pass them to child shell scripts.

**Comment by mnordsletten** [comment]
Sorry about that, I forgot to incorporate your changes. Good that you sorted it out. 

If this passes the jenkins tests I think it is ready to merge.

Jenkins test please

**Pull request merged**
