### PR TITLE
Added llvm to install_osx script

### PR DESCRIPTION
**Pull request by AndreasAakesson**
For issue #319. Introduced [homebrew](https://brew.sh) as dependency. It will now install llvm with brew, and use the clang/clang++ compiler from that installation. Also includes some cleanup inside script, and changes to reflect the changes made in `src/Makefile` (CC => CC_INC)

### CODE REVIEW

**Comment by alfred-bratterud** [comment]
Nice. Two things:

* Like I said in #319 I think it's better to have working, complete solutions than partial ones. The argument is that complete solutions can be automatically tested (We'll need to get a mac mini or a mac server that can run jenkins, and test this setup automatically). On Ubuntu the user is duely notified about the dependency installation, before the call to `sudo apt-get install`. Make sure we get a similar notification / confirmation from the user also on brew. Consider "./install_osx.sh -y" as a way to do this implicitly and let default be to ask for confirmation. 
* Since we're allready relying on brew, I think you might just as well refer directly to the binary in the cellar, like before, instead of making symlinks. Asking brew for the path is probably a robust way to get them.

@kybeg - you agree?

**Comment by kybeg** [comment]
Yes, i agree. Seems like this is a temporary solution in the big picture,
but pretty decent at the moment. Do we check that brew is installed in the
beginning?

**Comment by alfred-bratterud** [comment]
Yes, [Line 79](https://github.com/AndreasAakesson/IncludeOS/blob/master/etc/install_osx.sh#L79) checks for brew. @AndreasAakesson do you have time to do a couple of more commits on this? We'll probably do a cmake workshop after the holidays, for something more portable and robust.

**Comment by AndreasAakesson** [comment]
Sure, I'll make it a bit cleaner, and check for brew at the beginning.
@alfred-bratterud on your second point: This is the symlinks brew creating when installing (`/usr/local/opt/llvm/bin`). The reason I used this is because then I don't have to link directly to the version number of llvm (`/usr/local/Cellar/llvm/3.6.2/bin`). Maybe we can just directly ask brew for the path, I'll have a look.

**Comment by alfred-bratterud** [comment]
Hi @AndreasAakesson, that should be fine then, but I'm having these issues:
1. `make: *** No rule to make target `../api/os.hpp', needed by `kernel/kernel_start.o'.  Stop.`
2. ```make: clang++-3.6: No such file or directory
make: *** [vmbuild.o] Error 1``` 
[Complete output on gist](https://gist.github.com/alfred-bratterud/99348167e4541a14578a)

**Comment by alfred-bratterud** [comment]
Update: Ignore 1 - make clean fixes that one :-)

**Comment by kybeg** [comment]
@andreasaakesson, I got this (same?) error when testing ./etc/install_osx.sh from your IncludeOS repo (dev branch).

clang++-3.6 -MMD -target i686-elf -mrdrnd -msse3 -mstackrealign -O2 -DNO_DEBUG=1 -Wall -Wextra  -c -m32 -std=c++14 -fno-stack-protector -I../api/sys -I/Users/kyrre/IncludeOS_install/libcxx/include  -I/Users/kyrre/IncludeOS_install/newlib/include  -Iinclude -I../api  -D_LIBCPP_HAS_NO_THREADS=1 -DOS_VERSION="\"v0.7.0-proto-1-gfffbeb3\""  -o crt/cxxabi/cxa_default_handlers.o crt/cxxabi/cxa_default_handlers.cpp
make: *** [crt/cxxabi/cxa_aux_runtime.o] Error 127
/bin/sh: clang++-3.6: command not found
make: *** [crt/cxxabi/cxa_default_handlers.o] Error 127
boot/bootloader.asm:113: error: expression syntax error
boot/bootloader.asm:115: error: expression syntax error
boot/bootloader.asm:117: error: expression syntax error
boot/bootloader.asm:142: error: expression syntax error
make: *** [bootloader] Error 1

Do I have to create link from /usr/bin/clang++ to clang++3.6 myself?

**Comment by AndreasAakesson** [comment]
@alfred-bratterud Nice! Building vmbuild fails because the Makefile in vmbuild don't check for environment variables. I will add this.

@kybeg I'm working on my master branch, so use that one instead! I'm currently rewriting some big parts of the script.
Can you post all output on gist or something? Got some trouble pin point where it fails.
The bootloader fails because your nasm is outdated (I think). I'll thinking about adding that to the script aswell.
Can you check your version of nasm `$ nasm -v`?
And no, don't create a link. It shouldn't be needed with the current version (master branch).

**Comment by kybeg** [comment]
nasm -v: 
NASM version 0.98.40 (Apple Computer, Inc. build 11) compiled on Aug  7 2014

I removed the IncludeOS_build folder and ran the install script from master branch. I made a small change, in that I changed

#!/bin/bash

to 

#!/bin/bash -x

That help debugging in shellscripts!

Most of the output seemed to be OK, but the issues started at building IncludeOS:

>>> Building IncludeOS
+ pushd /Users/kyrre/work/IncludeOS/src
~/work/IncludeOS/src ~/work/IncludeOS
+ make -j4

>> Assembling bootloader
nasm -f bin -o bootloader boot/bootloader.asm


boot/bootloader.asm:113: error: expression syntax error
boot/bootloader.asm:115: error: expression syntax error
boot/bootloader.asm:117: error: expression syntax error
boot/bootloader.asm:142: error: expression syntax error
/usr/local/opt/llvm/bin/clang++ -MMD -target i686-elf -mrdrnd -msse3 -mstackrealign -O2 -DNO_DEBUG=1 -Wall -Wextra  -c -m32 -std=c++14 -fno-stack-protector -I../api/sys -I/Users/kyrre/IncludeOS_install/libcxx/include  -I/Users/kyrre/IncludeOS_install/newlib/include  -Iinclude -I../api  -D_LIBCPP_HAS_NO_THREADS=1 -DOS_VERSION="\"v0.7.0-proto-22-g48af7c1-dirty\""  -o crt/cxxabi/abort_message.o crt/cxxabi/abort_message.cpp
make: *** [bootloader] Error 1
make: *** Waiting for unfinished jobs....
/bin/sh: /usr/local/opt/llvm/bin/clang++: No such file or directory
make: *** [crt/cxxabi/abort_message.o] Error 127
+ make install


/usr/local/opt/llvm/bin/clang++ -target i686-elf -mrdrnd -msse3 -mstackrealign -O2 -DNO_DEBUG=1 -Wall -Wextra  -c -m32 -std=c++14 -fno-stack-protector -I../api/sys -I/Users/kyrre/IncludeOS_install/libcxx/include  -I/Users/kyrre/IncludeOS_install/newlib/include  -Iinclude -I../api  -D_LIBCPP_HAS_NO_THREADS=1 -DOS_VERSION="\"v0.7.0-proto-22-g48af7c1-dirty\""  -x assembler-with-cpp crt/crti.s -o crt/crti.o
/bin/sh: /usr/local/opt/llvm/bin/clang++: No such file or directory
make: *** [crt/crti.o] Error 127
+ popd
~/work/IncludeOS
+ echo -e '\n\n>>> Compiling the vmbuilder, which makes a bootable vm out of your service'


>>> Compiling the vmbuilder, which makes a bootable vm out of your service
+ pushd /Users/kyrre/work/IncludeOS/vmbuild
~/work/IncludeOS/vmbuild ~/work/IncludeOS
+ make
make: clang++-3.6: No such file or directory
make: *** [vmbuild.o] Error 1
+ cp vmbuild /Users/kyrre/IncludeOS_install/
cp: vmbuild: No such file or directory
+ popd
~/work/IncludeOS
+ echo -e '\n\n>>> Done! Test your installation with ./test.sh'


>>> Done! Test your installation with ./test.sh

**Comment by AndreasAakesson** [comment]
@kybeg I've added installation of nasm now, hopefully this will solve your problem. brew is required to install this.

**Comment by kybeg** [comment]
The nasm errors are gone, but this one is still there: 

/usr/local/opt/llvm/bin/clang++: No such file or directory

Is there another package missing? I think llvm is installed.

**Comment by AndreasAakesson** [comment]
That is weird. Do you have a folder called `/usr/local/opt`? That's where homebrew puts my link to the installation in `/usr/local/Cellar`. What about `/usr/local/bin`?

**Comment by AndreasAakesson** [comment]
With homebrew correctly setup (`/usr/local` with write access and `/usr/local/bin` in $PATH), exporting of environment variables is no longer needed.
Brew now installs specific version of llvm (3.6), which doesn't conflict with llvm installed native. `brew install llvm36` will put `clang-3.6 clang++-3.6` as symlinks in `/usr/local/bin`.

**Comment by kybeg** [comment]
OK. I seem to understand brew a little better now. clang++ was not installed. I had to run the following: 

brew install homebrew/versions/llvm36

Now things are improving and I got closer, but the installer stops at vmbuilder here: 

>>> Compiling the vmbuilder, which makes a bootable vm out of your service
~/work/IncludeOS/vmbuild ~/work/IncludeOS
vmbuild.cpp:22:10: fatal error: 'elf.h' file not found
#include <elf.h>
         ^
1 error generated.
make: *** [vmbuild.o] Error 1
cp: vmbuild: No such file or directory
~/work/IncludeOS

**Comment by fwsGonzo** [comment]
We should consider providing elf.h ourselves in the vmbuilder folder, since it's universal and only needed exactly there. It's not needed on Linux, but... on windows and mac it would be. So.. as far as I'm concerned, just click the paste button and commit it. Done. Any objections?

**Comment by alfred-bratterud** [comment]
We allready have elf.h - we just don't use it :-) It needs to be cleaned up a little to work with OSX, i.e. lose reference to features.h and one other.

**Comment by AndreasAakesson** [comment]
@kybeg I solved your problem by downloading *elf.h* [here](https://gist.github.com/mlafeldt/3885346) and added it to my include path, `/usr/local/include`. It's just a temporary solution tho. Could probably make the script fetch it aswell, what do you think @alfred-bratterud?

**Comment by alfred-bratterud** [comment]
Well, I guess I stand for what I said, that it's better to have a complete solution that works and can be automatically tested, rather than a partial one. So I'd say 1) fetch it 2) at the same time, remove the existing elf.h from our repo, and 3) add it to the list of what tell the user you'll do before you prompt.

**Pull request merged**
