### PR TITLE
profile: Don't link in stack sampler unless used

### PR DESCRIPTION
**Pull request by fwsGonzo**

### CODE REVIEW

**Comment by mnordsletten** [comment]
The storage test is failing due to the memdisk test. The third time it compiles this happens:

```
* <qemu>:  booting test_memdisk.img
* <qemu>:  Booting with multiboot (-kernel args)
* <qemu>:  KVM ON
* <qemu>:  command:
['qemu-system-x86_64', '--enable-kvm', '-kernel', u'test_memdisk', '-append', 'booted with vmrunner/Qemu', '-nographic', '-drive', u'file=test_memdisk.img,format=raw,if=ide,media=disk', '-m', '256']

* <VMRunner>:  Started process PID  27633
! <VM> ================================================================================
! <VM>
! <VM>                            #include<os> // Literally
! <VM>
! <VM> ================================================================================
! <VM>      [ Kernel ] Stack: 0x1f6d28
! <VM>      [ Kernel ] Boot args: 0x0 (multiboot magic), 0x9500 (bootinfo addr)
! <VM>                 * Low memory: 640 Kib
! <VM>                 * High memory: >= 65535 Kib
! <VM>      [ Kernel ] Assigning fixed memory ranges (Memory map)
! <VM>
! <VM> 	**** PANIC: ****
* <VMRunner>:  Stopping VM...
* <qemu>:  Stopping test_memdisk.img PID 27633


[ FAIL ] <VMRunner> terminating with uncaught exception of type Memory_range_exception: Start is larger than end: 134161961 > 68091903

```

**Comment by fwsGonzo** [comment]
Yes this is a known "issue", so, we will maybe work on this today, maybe not... We will just have to inform the VM somehow about how much memory it actually uses. The simplest way is to just run the memdisk test with multiboot enabled. (-kernel argument)

**Comment by alfred-bratterud** [comment]
test please

**Comment by AndreasAakesson** [comment]
retest please

**Pull request merged**
