### PR TITLE
Update Vagrantfile to use Ubuntu 16.04

### PR DESCRIPTION
**Pull request by xwvvvvwx**
- test.sh does not run on Ubuntu 14.04 (See issue #889)

### CODE REVIEW

**Comment by ingve** [comment]
Thanks! Do you know if this Vagrant box fixes the problem with VirtualBox being unable to mount synced folders, as mentioned in #530? (The bug report mentioned in the comment on that issue is still marked as "in progress" on Launchpad.)

**Comment by AndreasAakesson** [comment]
ok to test

**Comment by xwvvvvwx** [comment]
@ingve I didn't see that issue when I run locally. 

According to the launchpad linked on #530 this has been fixed since 20160907 ([see here](https://bugs.launchpad.net/cloud-images/+bug/1565985/comments/57)).

Running `vagrant up`, `vagrant ssh` work without error.
Inside the vm `./install.sh` and `./test.sh` run.

When I run `test.sh` I get the following error message after a while:

`[ DHCPv4 ] Negotiation timed out`

But the service seems to function correctly (I can `ping` it, and get the same response as defined in the test service when I run `curl` against the service)

Whats up with the failing tests? Anything I should worry about?

**Comment by ingve** [comment]
Very good news that the VirtualBox folder issue is fixed!

The failing tests are probably because your PR is directed to the master branch. Could you redirect it to the `dev` branch and see if the tests pass then?

**Comment by xwvvvvwx** [comment]
Done, all tests passing :)

**Pull request merged**
