### PR TITLE
support for multiple SHT_STRTAB sections in ELF. fixes #963

### LINKED ISSUE #963: elf_syms seg faulting
I'm trying to create a very simple service as a hello world to start from.  When using the Makefile from the demo_service example, everything seems to work until it calls elf_syms on the generated binary.  The seg fault is in line 94 (the one that calls `strlen(org)`).  My guess is that `org` isn't null-terminated, but I don't know enough about ELF formatted files to trace this down.  I would attach a copy of the binary if I could figure out how to do that inside GitHub.  What should I try to help debug the system?

### PR DESCRIPTION
**Pull request by szborows**
see #963 and Gitter for discussion

### CODE REVIEW

**Comment by fwsGonzo** [comment]
add to whitelist

**Comment by fwsGonzo** [comment]
seems like jenkins is having internet issues or something

**Comment by szborows** [comment]
can we re-run Jenkins jobs?

**Comment by ingve** [comment]
jenkins test please

**Comment by ingve** [comment]
Could you try redirecting this PR to the `dev` branch?

**Comment by szborows** [comment]
sure, done

**Comment by alfred-bratterud** [comment]
jenkins test please

**Pull request merged**
