### PR TITLE
Work towards making microLB test catch a nasty issue

### PR DESCRIPTION
**Pull request by fwsGonzo**
... which it does not, yet

### CODE REVIEW

**Comment by fwsGonzo** [comment]
Apparently it does

**Comment by alfred-bratterud** [comment]
Nice catch @fwsGonzo, thanks!

**Comment by alfred-bratterud** [comment]
Thanks @fwsGonzo - I tested these changes now and they're working for me.

**Comment by alfred-bratterud** [comment]
Looking to fix that LB test now, we'll merge when jenkins is green.

**Pull request closed without merging**
