### PR TITLE
First draft of IDE device driver implementation

### PR DESCRIPTION
**Pull request by yrakcaz**
Hi, I just have a few questions about it :

1) For the moment, the `IDE` class only handles the `master` device. Do you
    think that it could be interesting to handle the `slave` device too?
    If so, how could we give the information to the `IDE` class?

2) I don't have implemented the `write` function yet, how should I do that?
    I saw that in the `VirtioBlk` class it's the same thing, what about it? And shouldn't
    we have an Interface `IBlkDriver` which would be implemented by `IDE`, `VirtioBlk`
    and the other block devices?

3) Could you explain me a little how should the FileSystem work in IncludeOS?
   What if I want to bind the IDE with a FS? Shouldn't we make the `hw::Disk`
   class implement the `IDiskDevice` interface?

Cheers.

### CODE REVIEW

**Comment by fwsGonzo** [comment]
Cool stuff! It's probably not interesting to handle slave too, as we are aiming at supporting things minimally but fully (if that makes sense). Most VMs will only have one harddisk, so to speak, so only supporting master makes sense here.

Btw, is your solution async or possible to make async?

**Comment by fwsGonzo** [comment]
I see that its just polling. Fair enough. Want me to merge this?

**Comment by yrakcaz** [comment]
Ok great!

As I wrote in my commit message, I'll probably make it async using IRQs in a next commit,
like the write function and eventually FS things.

For the merge, as you prefer, but as this first version works I think it can be merged even
if it's not totally complete.

**Comment by fwsGonzo** [comment]
I'll have to make the connection between hw::Disk and the filesystem tomorrow then. I'll just merge this for now.

**Comment by yrakcaz** [comment]
Ok, so nothing more needed about the IDE driver except IRQ things, and removing the `write` function?

**Comment by fwsGonzo** [comment]
You wrote it, you defend it :)

Tomorrow, I'll take your IDE class and try to connect it to the filesystem. You don't have to push any changes immediately, and I won't be removing the write() proto so we don't get a conflict. We can talk more on gitter.im tomorrow if you want.

**Comment by yrakcaz** [comment]
Ok for me!

**Comment by alfred-bratterud** [comment]
Hi, nice work @yrakcaz, thanks :-) About `write` - good that you didn't implement ti yet!  As a general policy I we want to add all FS/Disk write-functionality as separate explicit includes. Alternatively, a minimal fs/disk that only does read, and another that does both, using the allready existing read functionality. This achieves two things: 
  * 1) we can say there is no code inside the OS that can write to the file system (we're want to make a platform suitable for [immutable infrasctructure](http://radar.oreilly.com/2015/06/an-introduction-to-immutable-infrastructure.html)) unless we explicitly asked for it
  * 2) Smaller images by default. We want small object files as a general rule, in order to get fine granularity. Say you want 10 features, and each feature has 2 unnecessary functions, you'll get 20 unnecessary functions in your image.

We can discuss the details on gitter.im tomorrow - looking forward to seeing more from you :+1:

**Pull request merged**
