### PR TITLE
inb and outb moved from kernel/os to hw/ioport

### PR DESCRIPTION
**Pull request by yrakcaz**
inb and outb are hardware communication things.
To be more proper, these calls are now in hw/ioport class.

### CODE REVIEW

**Comment by alfred-bratterud** [comment]
Can one of the admins verify this patch? Comment with "ok to test" to start the build or "add to whitelist" to add a trusted developer.

**Comment by alfred-bratterud** [comment]
Hi Zack, thanks for contributing! I agree with the move to hw. I'm not a 100% sure about the name `IOport` as we're trying to adhere to core guidelines which [recommends avoiding camel case](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rl-camel). But - I think this is better than having it in the OS class so I'll merge.  One suggestion: If you have time I wonder if it would actually be better to just use a namespace `hw`, and then have the functions called `hw::inb`/ `hw::outb`. @fwsGonzo, @RicoAntonioFelix @AndreasAakesson - your opinions?

**Comment by yrakcaz** [comment]
Hi! I guess I can do that.
So do you think that every classes contained in the `hw/` folder should be in that new `hw` namespace?

**Comment by fwsGonzo** [comment]
That sounds good. As for the inb and outb functions: They are largely inline assembly, 1-2 instructions, and don't deserve their own function calls imo. They could be inlined in your header, or as alfred wrote just (inline) functions in the hw namespace.

**Comment by yrakcaz** [comment]
Great, I'll make a new pull request soon.

**Comment by alfred-bratterud** [comment]
One important consideration is that we'll want support for other architectures at some point (read ARM). At that point all inline assembly has to be replaced. I guess there's no obious and pretty way to do that except by wrapping everything in macros. Any suggestions or thoughts on this, please shoot.

**Pull request merged**
