### PR TITLE
fix build with clang-3.9

### PR DESCRIPTION
**Pull request by noj**
- scoped enumerations cannot be shortened using 'using'.
- test 'clang' C compiler in CC detection in the Makefile.

### CODE REVIEW

**Comment by fwsGonzo** [comment]
Looks good to me

**Comment by fwsGonzo** [comment]
Looks good to me

test please

**Comment by mnordsletten** [comment]
Just thought I'd point out that this pull request is made towards our master branch.

**Comment by fwsGonzo** [comment]
Can you redirect this to dev @noj?

**Comment by noj** [comment]
Created a new pull request against dev #927

**Pull request closed without merging**
