### PR TITLE
Code Tweak[delegation.hpp]

### PR DESCRIPTION
**Pull request by FallingFromBed**

### CODE REVIEW

**Comment by ingve** [comment]
ok to test

**Comment by FallingFromBed** [comment]
`[ TIMEOUT ] vmrunner timed out after x seconds` is the error I see in most failure cases,Just contemplating how my change could cause it.

**Comment by ingve** [comment]
Thanks for contributing, @mnordsletten is investigating :)

**Comment by mnordsletten** [comment]
All services that I try to run with qemu hang as soon as I try to boot them. The tests that passed don't boot a service locally with qemu. 

I can't provide any good insight into what is causing the services to hang though.

**Comment by FallingFromBed** [comment]
Just for a clarification, I could see folks those who did pull req are all from dev branch and I believe it would be ok to give a pull from master.

**Comment by ingve** [comment]
It is usually better if you send your PRs to the `dev` branch, which has the latest fixes and most up-to-date code. Feel free to submit a new PR, and if you could give us some more info about the changes you are proposing, we should hopefully be able to help you figure out why the tests are failing.

**Pull request closed without merging**
