### PR TITLE
Make CPU features optional

### PR DESCRIPTION
**Pull request by AndreasAakesson**
See #1262

### CODE REVIEW

**Comment by AndreasAakesson** [comment]
So this turned out really ugly. Opinions about naming or how to do it is appreciated. Need a solution for `start.asm`

**Comment by mnordsletten** [comment]
The hping fail seems to be from two tests trying to access some resource at the same time. Highly random, so I will have to prevent this from happening. Jenkins test please

**Comment by mnordsletten** [comment]
This should be fixed now. There was an apt-get process running on the system when starting the test, thus failing all apt-get processes we started. It should now wait for the apt-get resource to be free.
Jenkins test please

**Comment by mnordsletten** [comment]
I wont make any promises anymore, but let's give it a go. Jenkins test please

**Pull request merged**
