### PR TITLE
Augmented file api/fs/common.hpp

### PR DESCRIPTION
**Pull request by RicoAntonioFelix**
# Changes
* Added API DOC 
* Refactored methods

### CODE REVIEW

**Comment by fwsGonzo** [comment]
Looks good, we will test it today and merge if it works :+1:

**Comment by mnordsletten** [comment]
Ok to test
To check if the new pull request stress test works.

**Comment by mnordsletten** [comment]
Ok to test
To check if the new pull request stress test works.

**Comment by mnordsletten** [comment]
Ok to test
To check if the new pull request stress test works.

**Pull request merged**
